version: "3"
services:
  pms:
    build: .
    restart: always
    volumes:
      - ./site:/site
    environment:
      - ADMIN_EMAIL=admin@admin.ru
      - ADMIN_PWD=12345
      - DB_SECRET=MOSTSECUREKEY

  db:
    image: mongo
    restart: always
